### ISSUE TITLE
Don't support download-on-every-run

### ISSUE THREAD

**Issue by topaz** [ksmithut/advent-of-code#1]
Letting the user grab their input once during init is probably safe.  Encouraging them to request it _every time they run their code_ is unacceptable and irresponsible.  No input endpoint ever returns something different for a given session - please please save the result to disk and reuse it.

**Comment by ksmithut** [comment]
Alright, I'll attempt to have this done tonight, but I'll for sure have it done by the end of day today. Apologies for any harmful traffic that this may have caused. Do you have any suggestions for clearing the cache? Or should I just provide docs on where they might search for the cache so they can delete it manually (in the case that they switch users or something).

**Comment by topaz** [comment]
Just tell the user where the files are; you could even have output during execution that says something like "Found existing day12/input; not downloading again." to indicate where the file is you're using.

**Comment by ksmithut** [comment]
While I'm at it, is there something specific you'd like me to set as the user agent to make it easier for you to determine requests that come from this module?

**Comment by topaz** [comment]
Setting the user agent would be excellent; anything that identifies the NPM package or this Github repo is probably fine.

**Comment by ksmithut** [comment]
Alright, I've published a new version, 2.0.0 with the user agent, also supporting local caching so it should only have to make a request for input once per puzzle.

I also updated the readme with a note about debugging. There is now an environment flag that will output debug messages about where and when it reads from the cache (amongst other things). I also put a note in there that if it is found that this module is abusing adventofcode.com, it will be removed from here and from npm. If you'd rather, I can just remove it completely before it ever gets popular and I can just use it personally. I don't want to be the cause of abuse of your system.

**Comment by ksmithut** [comment]
Oh, the user agent set will be `node/{node version} advent-of-code/{package version}`. If you'd like me to add anything else to this, let me know, or PRs are also welcome :)

**Comment by topaz** [comment]
If it caches, it will be fine; the scariest part was "request every time you run", which is fine with caching.

**Comment by ksmithut** [comment]
Awesome :) Let me know if you have any more suggestions or feedback.
